version: '3'

services:
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes:
      - './logs/nginx/:/var/log/nginx/'
      - '.:/var/www'
      - './docker/nginx/sites:/etc/nginx/sites-available'
      - './docker/nginx/certs:/etc/nginx/certs'
    ports:
      - 80:80
      - 443:443
    networks:
      - backend
  php-pm:
    build:
      context: docker/php-pm
      dockerfile: Dockerfile
    volumes:
      - '.:/var/www'
    networks:
      - backend
    ports:
      - 8000:8000

networks:
  backend:
    driver: bridge
